### ISSUE TITLE
Add close button

### ISSUE THREAD

**Issue by winzortdusmani** [JGeek00/adguard-home-manager#127]
![Ekran Görüntüsü (6)](https://github.com/JGeek00/adguard-home-manager/assets/75412448/e19724cd-c429-475c-bcca-b24fbcb53120)

also a close button can be added, or it can close when the empty space is clicked.

**Comment by winzortdusmani** [comment]
As far as I noticed, for example, there is no close button in the add blacklist and add whitelist. but when clicked in the empty space, the tab closes.

**Comment by JGeek00** [comment]
You can close it by clicking on the apply button

**Comment by winzortdusmani** [comment]
> You can close it by clicking on the apply button

Yes, it can be closed like that. But as I said in the whitelist and blacklist. Optional

**Comment by JGeek00** [comment]
That's right. I disabled closing the modal by clicking on the overlay specially for this modal because in order to apply the filters and trigger the request, the user has to click on Apply. So if you want to close the modal (to always apply the selected filters) you have to click on Apply. If you just want to discard the selected filters, just reset the filters to default values and click on apply.

**Comment by winzortdusmani** [comment]
Got it, thanks
