### ISSUE TITLE
[Suggestion] Some changes to improve usability 

### ISSUE THREAD

**Issue by zekabra** [JGeek00/adguard-home-manager#20]
Hello, here are some suggestions to make the app even more usable. In the list of top queried domains and top blocked domains, be possible to click on an entry and be able to choose to block or allow depending on the list. In filters/custom rules, have an icon next to the entry to provide a visual indication if the entry is a permission or a blocking, use the icons that already appear in the black list. Be able to edit the entry, currently if I want to edit an entry, I have to delete it and create it again. Thanks for the great app, it has been of great use.

**Comment by whinnla** [comment]
More advanced log search functionality.
Like searching by client and domain at the same time

**Comment by JGeek00** [comment]
I have released v1.6.0 adding some of these features. Now you can long press an entry on top items to block or unblock a domain and on custom rules now there's a text that points if the rule is a blocking rule, an allowing rule or a comment. I didn't added an option to edit a custom rule because the AdGuard Home REST API doesn't have that option.
