### ISSUE TITLE
[Bug] Blank window in logs list

### ISSUE THREAD

**Issue by zekabra** [JGeek00/adguard-home-manager#22]
Sorry to bother you with another bug, I really like the application and wish to see everything working properly. In the logs list any entry that has been manually added in filters/custom rules, when clicked shows a blank window and does not allow you to see the information. As a suggestion, a nice feature to have would be when you long click on an entry, the domain is copied to the clipboard, so it would be easier to make a manual entry in custom rules.

https://user-images.githubusercontent.com/24387750/204884225-f36f78e4-581a-4335-9e41-9314d4916669.mp4

**Comment by JGeek00** [comment]
Hi. Thanks for reporting the issue. I think I know what's causing that.
Please, when you find a log that causes that grey screen, follow the next tutorial.

https://user-images.githubusercontent.com/47545344/204898851-2d65d553-89f3-49c1-b661-eab1da363a39.mp4

Basically, when you find on the app a log that causes a greyscreen, find on the logs list that exact entry (you can find the domain as it's shown on the video), copy the object and paste it here. If you think that contains sensible data, replace that data with other stuff, but do not remove anything (if there's special data like dates for example, don't change it).

Regarding the feature request, please open a separate issue for it. To have a better tracking. 

As I can see, you are a tablet user. The next big update will introduce an interface designed for tablets, but I have to wait to release it because the Flutter team has to fix some bugs on the new Material 3 components.

**Comment by zekabra** [comment]
>Basically, when you find on the app a log that causes a greyscreen, find on the logs list that exact entry (you can find the domain as it's shown on the video), copy the object and paste it here. If you think that contains sensible data, replace that data with other stuff, but do not remove anything (if there's special data like dates for example, don't change it).
> 

> {
    "answer": [
        {
            "type": "AAAA",
            "value": "::",
            "ttl": 10
        }
    ],
    "answer_dnssec": false,
    "cached": false,
    "client": "192.168.1.104",
    "client_info": {
        "whois": {},
        "name": "Pad5",
        "disallowed_rule": "192.168.1.104",
        "disallowed": false
    },
    "client_proto": "",
    "elapsedMs": "3.690577",
    "filterId": 0,
    "question": {
        "class": "IN",
        "name": "fr.app.chat.global.xiaomi.net",
        "type": "AAAA"
    },
    "reason": "FilteredBlackList",
    "rule": "||fr.app.chat.global.xiaomi.net^",
    "rules": [
        {
            "filter_list_id": 0,
            "text": "||fr.app.chat.global.xiaomi.net^"
        }
    ],
    "status": "NOERROR",
    "time": "2022-11-30T21:50:17.174807591Z",
    "upstream": ""
}

Here is how this situation happens, I go to the log and look for an entry that I want to block or allow, I click on the entry to see more information, then I click on the top left corner to allow or block, after that every time I find that domain in the logs and click it, this happens, always a grey screen for all the entries I added this way

**Comment by JGeek00** [comment]
I think I have fixed the issue. Please try this version and let me know if the issue is gone.
[test.zip](https://github.com/JGeek00/adguard-home-manager/files/10127790/test.zip)

**Comment by zekabra** [comment]
It's fixed, tks again for the excellent support

**Comment by JGeek00** [comment]
Thank you for reporting the issues you find.
