### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by DschungelDaddy** [JGeek00/adguard-home-manager#37]
Hi,
I am using my ADGuard Home behind a "Basic Auth" login page.
It would be nice to include this authentication method in the server setting.
Thanks
DD

**Comment by DschungelDaddy** [comment]
These are two separate login processes.
1.) Basic Auth to get to AdGuard login page
2.) AdGuard Login
DD

**Comment by JGeek00** [comment]
I'm not sure if that's possible. When you send a request to the AdGuard Home API you have to include on the request an ``Authorization`` header with the value ``Basic <your token>`` (the token is generating by encoding username:password with base64). When you send a request to an API that is protected with a basic auth you have to include on the request that same header with the value encoded on the same way, but with the authentication values of the basic auth, so I don't know if it's possible to send a request with two ``Authorization`` headers or to send an ``Authorization`` header with two values.
The web UI works on a different way. It doesn't use the ``Authorization`` header to send the requests to the API, so in that situation adding a basic auth on top of that it's not a problem.

**Comment by DschungelDaddy** [comment]
Hi,

how the whole thing runs in the background, I can not say :)

I only know that my "piHole" (com.tien.piholeconnect) app has this function and it works 100%. 

DD

**Comment by JGeek00** [comment]
> Hi,
> 
> 
> 
> how the whole thing runs in the background, I can not say :)
> 
> 
> 
> I only know that my "piHole" (com.tien.piholeconnect) app has this function and it works 100%. 
> 
> 
> 
> DD

Hi. The Pi-Home API authentication works on a completely different way. 

Just for adding some context. When you want to send an HTTP request to an endpoint that is protected with a basic auth, you have to send the ``Authorization`` header with the content ``Basic <token>`` and the token is ``username:password`` encoded in base64.

The AdGuard Home's API auth system uses the Authorization header to authenticate the user, so you don't have available the ``Authorization`` header for the basic auth. The web interface can work with a basic auth because the web interface does not use the ``Authorization`` header to authenticate the user, but if you want to interact with the API from a third party app, you have to use that ``Authorization`` header.

On the other hand, the Pi-hole API works on a different way. There you send the auth token via a query parameter. 
Example: ``domain.com/pihole?auth=xxxxxxxxx``, so on this situation you have available the ``Authorization`` header.

I have also developed a Pi-hole client and on that app, I added support for servers with basic auth, but on the case of AdGuard Home, that's not possible.
