### ISSUE TITLE
Set system navigation bar color to use the same one as the navigation bar background color

### ISSUE THREAD

**Issue by marek-guran** [JGeek00/adguard-home-manager#75]
The bottom navigation space could have background color of bottom navigation menu so it looks more "nicer". In android studio you add in light and dark theme this (don't know how dart does this so can't make PR):

```xml
<item name="android:navigationBarColor">@color/nav_menu_color</item>
```

![Screenshot_20231117-233013.png](https://github.com/JGeek00/adguard-home-manager/assets/26904790/c3d6cea1-791c-44ac-9a36-fb9de2dce765)

![Screenshot_20231117-233039.png](https://github.com/JGeek00/adguard-home-manager/assets/26904790/34005073-21e8-49ab-8390-be8d18b1f0c3)

**Comment by JGeek00** [comment]
Hi. For now I cannot change that color because the Flutter framework still has some of the Material 3 colors missing. If you check the [Material 3 navigation bar specifications](https://m3.material.io/components/navigation-bar/specs), the background color that the navigation bar uses for the background is `surface-container`, however, that color is missing on the current Flutter Material 3 palette. Check this issue on the Flutter framework repo: https://github.com/flutter/flutter/issues/115912. I will change the system navigation bar color as soon as the `surface-container` is added to the Flutter framework Material 3 palette.

**Comment by JGeek00** [comment]
Hi @rydmike thank you for the suggestion. Finally I opted for the first option, because it works better with modal bottom sheets. The problem is that the edge to edge mode doesn't affect to the traditional navigation bar, but with the gestures bar it works fine.

Finally I have mixed both methods. I use the first one for gestures navigation, and the second one for the traditional buttons navigation.

```dart
final systemGestureInsets = MediaQuery.of(context).systemGestureInsets;

    return AnnotatedRegion<SystemUiOverlayStyle>(
      value: SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarBrightness: Theme.of(context).brightness == Brightness.light
          ? Brightness.light
          : Brightness.dark,
        statusBarIconBrightness: Theme.of(context).brightness == Brightness.light
          ? Brightness.dark
          : Brightness.light,
        systemNavigationBarColor: systemGestureInsets.left > 0  // If true gestures navigation
          ? Colors.transparent
          : ElevationOverlay.applySurfaceTint(
              Theme.of(context).colorScheme.surface, 
              Theme.of(context).colorScheme.surfaceTint, 
              3
            ),
        systemNavigationBarIconBrightness: Theme.of(context).brightness == Brightness.light
          ? Brightness.dark
          : Brightness.light,
      ),
      child: child,
    );
```

![Screenshot_1702090493](https://github.com/JGeek00/adguard-home-manager/assets/47545344/ebec79b2-3ab1-41e1-8285-f07a2fda8694)

**Comment by rydmike** [comment]
That's a good idea.

The edge to edge feature works on newer versions of Android with the 3 or in some cases 2 nav button system top, but yes on older versions it does not, that is a limitation in Android version.

There is info in Flutter issues from which version it is supposed to work from, as I recall when I investigated the version Flutter mentioned was not correct, I seem to recall I need one version higher than they mentioned before it started working. It requires quite a new Android version to work. I can dig up the issue threads where it is discussed, if it is still of interest.

Anyway glad if my hints helped and you found a solution that works for you 👍🙂

**Comment by JGeek00** [comment]
I think that the issue with the color of the system navigation bar when it's on the three buttons mode it's still present on Android 14, because I switched from the gestures navigation to the three buttons navigation and the bar was white.
