### ISSUE TITLE
Submit to F-Droid

### ISSUE THREAD

**Issue by Generator** [JGeek00/adguard-home-manager#8]
Release it on F-Droid, it gets more visibility on self-hosted community and other users.

https://f-droid.org/docs/Submitting_to_F-Droid_Quick_Start_Guide

**Comment by JGeek00** [comment]
Hi! I will consider it, but for now it will only be available at Google Play. If you don't want to download it from Google Play, you can get de APK from the releases section of this repo.

**Comment by JGeek00** [comment]
The app has an integrated notification system to alert the user when a new version is released and the app is installed from outside Google Play. I don't think it's necessary to release the application on F-Droid. Also, I don't want to have the application spread over multiple sources. The main source to get the application is Google Play, and it's also available on GitHub for those who don't want to download it through Google Play, because it very easy to upload a new release and I can do it very quick with very little effort.
